### ISSUE TITLE
TextHandler Object ERROR

### ISSUE THREAD

**Issue by crazytaxzi** [generalwrex/HellionExtendedServer#7]
When it is only one player on the server, Everything is beautiful. After a second player logs in I get this error when ever someone sends a chat message.

------------------------------------------------------------------------------
2017/03/03 02:46:28.4882 - [ERROR] Object reference not set to an instance of an object.
   at HellionExtendedServer.Controllers.NetworkController.TextChatMessageListener(NetworkData data)
   at ZeroGravity.Network.EventSystem.NetworkDataDelegate.Invoke(NetworkData data)
   at ZeroGravity.Network.EventSystem.InvokeQueuedData()
   at ZeroGravity.Server.UpdateData(Double deltaTime)
   at ZeroGravity.Server.MainLoop()
	 Ln 0 Col 0
------------------------------------------------------------------------------

Dell 2950 2u Rack Mount
Dual Intel Xeon Quad Core Proc 3.0ghz
16gb ram
Windows 7 Pro

**Comment by crazytaxzi** [comment]
Update:
After server player count gets back down to 1 player then chat works great again.

**Comment by generalwrex** [comment]
Thanks for the bug report! I'll look into it!

**Comment by generalwrex** [comment]
Could you join          
Server name: ! {XTT}[US-Little Rock] [HellionExtendedServer] Hellion Service Development #2
I currently don't have anyone else to help me increase the player count ;)

**Comment by generalwrex** [comment]
Does it still do it on this one? - https://github.com/generalwrex/HellionExtendedServer/releases/tag/0.0.1.6-fix

**Comment by crazytaxzi** [comment]
Just updated server to latest release of HES. I will keep an eye on the logs thank you for the fast response.
